apiVersion: admissionregistration.k8s.io/v1
kind: MutatingAdmissionPolicy
metadata:
  name: filter-match-labels
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
  mutations:
    - patchType: JSONPatch
      jsonPatch:
        expression: >-
          [
            JSONPatch{
              op: "add",
              path: "/spec/affinity",
              value: Object.spec.affinity{
                podAntiAffinity: Object.spec.affinity.podAntiAffinity{
                  requiredDuringSchedulingIgnoredDuringExecution: [
                    Object.spec.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution{
                      topologyKey: "kubernetes.io/hostname",
                      labelSelector: Object.spec.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution.labelSelector{
                        matchLabels: object.metadata.labels.transformMap(k, v, k != "foo", v)
                      }
                    }
                  ]
                }
              }
            }
          ]
