apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: match-resources
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      operations: ["CREATE"]
      resources: ["pods"]
    - apiGroups: ["apps"]
      apiVersions: ["v1"]
      operations: ["UPDATE"]
      resources: ["deployments"]
    - apiGroups: ["networking.k8s.io"]
      apiVersions: ["v1"]
      operations: ["CREATE"]
      resources: ["networkpolicies"]
    excludeResourceRules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      operations: ["CREATE"]
      resources: ["pods"]
      resourceNames: ["exempt-pod"]
    objectSelector:
      matchExpressions:
      - key: skip-policy
        operator: DoesNotExist
  validations:
  - expression: "has(object.metadata.labels) && 'owner' in object.metadata.labels"
    message: "owner label is required"
    reason: Invalid
