apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingAdmissionPolicy
metadata:
  name: sidecar-injection
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      operations: ["CREATE"]
      resources: ["pods"]
  mutations:
  - patchType: JSONPatch
    jsonPatch:
      expression: |
        [
          JSONPatch{
            op: 'add',
            path: '/spec/containers/-',
            value: {
              'name': 'istio-proxy',
              'image': 'istio/proxyv2:1.20.0',
              'ports': [{'containerPort': 15090, 'protocol': 'TCP', 'name': 'http-envoy-prom'}]
            }
          }
        ]
  matchConditions:
  - name: 'has-inject-label'
    expression: "has(object.metadata.labels) && 'sidecar.istio.io/inject' in object.metadata.labels && object.metadata.labels['sidecar.istio.io/inject'] == 'true'"

